import type { Metadata } from "next";
import ClientLayoutProvider from "@/src/components/providers/ClientLayoutProvider";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ClientLayoutProvider>{children}</ClientLayoutProvider>
      </body>
    </html>
  );
}
